### ISSUE TITLE
【レビュー依頼】MVPリリース 2024.11.18

### ISSUE THREAD

**Issue by moguDev** [moguDev/flully#60]
## サービス概要
サービス名：flully（ふらり）
サービスURL：[flully.jp](https://flully.jp)

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x]  環境構築（Next.js / Rails / Docker）
- [x]  デプロイ（Vercel / Render.com）
- [x]  トップページ
- [x]  ユーザー登録 / ログイン機能
- [x]  さんぽの記録機能
- [x]  みつけた動物の投稿・閲覧機能
- [x]  掲示板の作成・閲覧機能
- [x]  みつけた動物・掲示板へのコメントの投稿
- [x]  マイページ
- [x]  独自ドメイン
- [x]  レスポンシブ対応
- [x]  静的OGP
- [ ]  動的OGP **（本リリースで実装に変更）**

### **動的OGPの設定を本リリースに変更しました。**
動的OGPのシェアには力を入れたいと考えおり、それに伴いデザインなどにも拘りたいと考えいるため、本リリースまで主にデザイン面の構想に時間をいただきたく、本リリースにて実装予定と調整されていただきました。
なお静的OGPに関しては生成ずみのため、「みつけた動物」や「掲示板」のシェア時にはアプリの静的OGPが適用される形と現状はなっております。

### **トップページの掲載情報の一部を本リリース時に実装に変更しました。**
実装予定であった「アプリの主な機能」「アプリの使い方」などの情報の掲載を本リリースに変更させていただきたく考えております。

## サービスイメージがわかるようなスクリーンショット等
【基本マップ画面】
<img src="https://i.gyazo.com/14ef8ec624cdbbbb1e689a9c5b1ad732.jpg" width="200px" />
【近くの情報・投稿の表示】
<img src="https://i.gyazo.com/ec45a21bd38eca8ab5b99533a6e4b670.jpg" width="200px" />
【みつけた動物の詳細表示】
<img src="https://i.gyazo.com/01f14c2f5942c88d1b3bdf1b00a50fa5.jpg" width="200px" />
【見つけた動物のコメント表示】
<img src="https://i.gyazo.com/a33fb86b5b01f5a5351ff0d18f3e6770.png" width="200px" />
【掲示板一覧の表示】
<img src="https://i.gyazo.com/141729096bba224d943aa50fcbe690fc.png" width="200px" />
【掲示板の詳細の表示】
<img src="https://i.gyazo.com/48ec6b94715062e1520d688682c47646.jpg" width="200px" />
【掲示板のコメントの表示】
<img src="https://i.gyazo.com/b9cb8df3b7785bd2b2e41267f599788b.jpg" width="200px" />
【マイページの表示】
<img src="https://i.gyazo.com/cb9e3d12dd420754603dd03e84eb3adb.png" width="200px" />

レスポンシブ含めUI面のディティールの調整やトップページの構想に想定以上に時間がかかってしまい予定していたレビュー予定日より遅れてのご提出となってしまいました。
申し訳ございません。

上記の内容にレビューの依頼とされていただきます。
ご確認の程よろしくお願いいたします！

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです！！！（クオリティ高過ぎ！）
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by moguDev** [comment]
@TakenakaEri さん
さっそくのレビューありがとうございます！
上記承知いたしました！よりよりサービスとして本リリースできる頑張ります。
引き続きよろしくお願いいたします！
