### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by moguDev** [moguDev/flully#8]
## ■ Webアプリの概要
flullyは散歩した距離やルートを記録かつ散歩中にみた動物の情報を共有できるアプリケーションです。散歩した距離によって取得できるポイントによってユーザレベルが上がっていき、他ユーザとランキングを通じて競うゲームのような体験を提供します。

ユーザは迷子のペットや保護したペットの情報を投稿することができます。マップUI上で近くで迷子になったペット情報が表示され、散歩中に発見した場合、写真や目撃情報を投稿することができ、迷子になったペットがお家に無事に帰れるようサポートします。

またユーザが散歩中に発見した動物の情報の共有を促すことにより、まいごのペットの捜索にも繋がります。また「迷子情報を見る」や「迷子情報をXでシェアする」などのデイリーミッションをこなすことで散歩後に取得できるポイントが増加しするなど、迷子の捜索の貢献につながるアクションをインセンティブ付きで提案します。

## ■ 1週間辺りの開発に向けられる時間
- 1週間あたり：70〜84時間（ストーリーポイント：35〜42）

## ■ ProjectsのURL
[flully開発プロジェクト - RUNTEQ卒業制作](https://github.com/users/moguDev/projects/1/views/1)

## ■ MVPリリースまで
- [x] 環境構築（Next.js / Rails / Docker）
- [x] デプロイ（Vercel / Render.com）
- [x] トップページ
- [x] ユーザー登録 / ログイン機能
- [x] さんぽの記録機能
- [x] みつけた動物の投稿・閲覧機能
- [x] 掲示板の作成・閲覧機能
- [x] みつけた動物・掲示板へのコメントの投稿
- [x] マイページ
- [x] 独自ドメイン
- [x] レスポンシブ対応
- [x] 静的OGP
- [ ] 動的OGP

## ■ MVP後
- [ ] OAuth（Sign in with Google）
- [ ] トップページ完成
- [ ] ファビコン設定
- [ ] お知らせ機能
- [ ] ユーザレベル機能
- [ ] デイリーミッション機能
- [ ] ランキング機能
- [ ] ユーザ間のフォロー機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] ネコサーチAPIによる迷子情報取得
- [ ] スマートフォン・タブレット端末でのみ散歩が開始できるように
- [ ] RSpec導入

## ■ MVPレビュー依頼予定日
予定日：~~2024年11月15日(金)~~ → 2024年11月18日(月)

**Comment by tarakish** [comment]
確認しました👍️
以下ご対応をお願いします！
- 各カードはIssue化してください
- （Issue化した）カードの内容がなかったので、そのIssueを実現するために必要なタスクをそれぞれ記載するようにお願いします

**Comment by moguDev** [comment]
レビューいただきありがとうございます！
下記対応いたしました、お手数ですが改めてレビューをお願いいたします。

- [x] 各カードのIssue化
- [x] MVPまでの各カードにタスクの記載

**Comment by kenchasonakai** [comment]
LGTMです！
